services:
  ai-image-detector:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-image-detector
    container_name: ai-image-detector
    ports:
      - "5002:5002"
    volumes:
      - ./files:/app/files
    command: ["python", "/app/files/app.py"]
    restart: unless-stopped
